_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NUM_CLASSES: 1041

  LOSSES:
    TRI:
      MARGIN: 0.3

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

SOLVER:
  MAX_ITER: 28000
  DELAY_ITERS: 14000
  WARMUP_ITERS: 4700
  FREEZE_ITERS: 4700

TEST:
  EVAL_PERIOD: 5000
  PRECISE_BN:
    DATASET: 'MSMT17'

OUTPUT_DIR: "logs/msmt17/sbs_S50"
