_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/bagtricks_S50"
