_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NUM_CLASSES: 702

  LOSSES:
    TRI:
      MARGIN: 0.3

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

TEST:
  PRECISE_BN:
    DATASET: 'DukeMTMC'

OUTPUT_DIR: "logs/dukemtmc/sbs_S50"
