_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NUM_CLASSES: 751

  LOSSES:
    TRI:
      MARGIN: 0.3

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs_S50"
